fix building
Valian/docker-python-opencv-ffmpeg pull request #2
Opened 2018-08-19 07:47 UTC by Borda

* upgrade to ubuntu 16.04 LTS
 * fix build for python3
 * fix build for CUDA
 * update README

Note, the actual version with ubuntu 16.10 does not have valid packages and also the Python3, as well as both CUDA versions, fail to build. There is a refactoring which makes the code easier to read...

2018-08-21 23:02 UTC, Borda commented
@Valian ^^

2018-09-01 12:22 UTC, Valian requested changes
I really like your changes, formatting and README is much better now, and it looks like build is working again ^^ Just fix merge conflicts and a couple of minor problems, and I will happily merge it :+1: Sorry for delay!

2018-09-01 12:22 UTC, Valian commented on Dockerfile-py2-cuda
> +CMD ["python --version"]
Add newline at the end of files

2018-09-01 12:22 UTC, Valian commented on Dockerfile-py2
> -LABEL maintainer "jakub.skalecki@gmail.com"
I would like to keep this label :smile:

2018-09-02 19:31 UTC, Borda commented on Dockerfile-py2-cuda
> +CMD ["python --version"]
ok, added :)

2018-09-02 19:37 UTC, Valian approved these changes

2018-09-02 19:38 UTC, Valian commented
Thank you, approving!

2018-09-02 19:38 UTC, merged

2018-09-03 08:04 UTC, Borda commented
@Valian maybe you could consider rebuilding images on docker hub... :)

2018-09-03 10:29 UTC, Valian commented
@Borda I've started builds https://hub.docker.com/r/valian/docker-python-opencv-ffmpeg/builds/, but I think some of them will fail due to timeouts. If it will be the case, I'll either setup some kind of CI or build it manually and push to DockerHub (Yes, I know this solution would be temporary at best)